Vagrant.configure("2") do |config|
  config.vm.define "webdev" do |webdev|
	webdev.vm.box = "centos/7"
	webdev.vm.hostname = "webdev01"
	webdev.vm.network "private_network", ip: "10.11.11.100", netmask: "255.255.255.0" 
		webdev.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", 1, "--name", "webdev01"]	
		end
    webdev.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    end    
    webdev.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "Provisioning/setup.yaml"
        ansible.install_mode = "default"
        
    end
  end
end
